Update configuration files (#93)
* Update TFLint rule versions

Signed-off-by: Roman Schwarz <rs@cloudeteer.de>

* Update pre-commit hook refs

Signed-off-by: Roman Schwarz <rs@cloudeteer.de>

* Add missing comparison for TFLint test config file

Signed-off-by: Roman Schwarz <rs@cloudeteer.de>

* Remove unused pre-commit configuration file

Signed-off-by: Roman Schwarz <rs@cloudeteer.de>

* Move module-ci configuration files into config subdirectory

Signed-off-by: Roman Schwarz <rs@cloudeteer.de>

* Rename step name to more descriptive name

Signed-off-by: Roman Schwarz <rs@cloudeteer.de>

* Print warning if terraform-docs config file differs from expected (#91)

Signed-off-by: Roman Schwarz <rs@cloudeteer.de>

---------

Signed-off-by: Roman Schwarz <rs@cloudeteer.de>

diff --git a/.github/workflows/module-ci-documentation.yaml b/.github/workflows/module-ci-documentation.yaml
--- a/.github/workflows/module-ci-documentation.yaml
+++ b/.github/workflows/module-ci-documentation.yaml
@@ -18,19 +18,21 @@ jobs:
           path: .terraform-governance
           repository: cloudeteer/terraform-governance
           sparse-checkout-cone-mode: false
-          sparse-checkout: terraform-docs.yaml
+          sparse-checkout: config/terraform-docs.yaml
 
       - name: Compare terraform-docs configuration files
         continue-on-error: true
         run: |
-          diff -u .terraform-governance/terraform-docs.yaml .terraform-docs.yaml
-          result=$?
-
-          if [ $result -eq 1 ]; then
+          if diff -u .terraform-governance/config/terraform-docs.yaml .terraform-docs.yaml > /dev/null; then
+            echo "No differences found in terraform-docs.yaml"
+          else
+            result=$?
+            if [ $result -eq 1 ]; then
             echo "::warning::Your local .terraform-docs.yaml file is different from the default one in the cloudeteer/terraform-governance repository. Please update your configuration file accordingly to make sure you have consistent documentation results."
-          elif [ $result -ge 1 ]; then
-            exit $result
+            elif [ $result -gt 1 ]; then
+              echo "::error::An error occurred while comparing .terraform-docs.yaml files."
+            fi
           fi
 
       - name: Check for diff in terraform-docs
-        run: terraform-docs . --config .terraform-governance/terraform-docs.yaml --output-check
+        run: terraform-docs . --config .terraform-governance/config/terraform-docs.yaml --output-check
diff --git a/.github/workflows/module-ci-lint.yaml b/.github/workflows/module-ci-lint.yaml
--- a/.github/workflows/module-ci-lint.yaml
+++ b/.github/workflows/module-ci-lint.yaml
@@ -16,16 +16,16 @@ jobs:
         with:
           terraform_version: ${{ steps.terraform_version.outputs.required_version }}
 
-      - name: Checkout tflint.hcl
+      - name: Checkout TFLint config files from terraform-governance repository
         uses: actions/checkout@v4
         with:
           path: .terraform-governance
           repository: cloudeteer/terraform-governance
           sparse-checkout-cone-mode: false
           sparse-checkout: |
-            tflint.hcl
-            tflint.examples.hcl
-            tflint.tests.hcl
+            config/tflint.hcl
+            config/tflint.examples.hcl
+            config/tflint.tests.hcl
 
       - name: Setup TFLint
         uses: terraform-linters/setup-tflint@v4
@@ -36,8 +36,11 @@ jobs:
       - name: Compare TFLint configuration files
         continue-on-error: true
         run: |
+          ls -al ./
+          ls -al .terraform-governance/
+
           # Compare tflint.hcl
-          if diff -u .terraform-governance/tflint.hcl .tflint.hcl > /dev/null; then
+          if diff -u .terraform-governance/config/tflint.hcl .tflint.hcl > /dev/null; then
             echo "No differences found in tflint.hcl"
           else
             result=$?
@@ -47,9 +50,9 @@ jobs:
               echo "::error::An error occurred while comparing .tflint.hcl files."
             fi
           fi
-          
+
           # Compare tflint.examples.hcl
-          if diff -u .terraform-governance/tflint.examples.hcl .tflint.examples.hcl > /dev/null; then
+          if diff -u .terraform-governance/config/tflint.examples.hcl .tflint.examples.hcl > /dev/null; then
             echo "No differences found in tflint.examples.hcl"
           else
             result=$?
@@ -60,13 +63,25 @@ jobs:
             fi
           fi
 
+          # Compare tflint.examples.hcl
+          if diff -u .terraform-governance/config/tflint.tests.hcl .tflint.tests.hcl > /dev/null; then
+            echo "No differences found in tflint.tests.hcl"
+          else
+            result=$?
+            if [ $result -eq 1 ]; then
+              echo "::warning::Your local .tflint.tests.hcl file is different from the default one in the cloudeteer/terraform-governance repository. Please update your configuration file accordingly to make sure you have consistent documentation results."
+            elif [ $result -gt 1 ]; then
+              echo "::error::An error occurred while comparing .tflint.tests.hcl files."
+            fi
+          fi
+
       - name: Init TFLint
-        run: tflint --init --config=.terraform-governance/tflint.hcl
+        run: tflint --init --config=.terraform-governance/config/tflint.hcl
         env:
           # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
           GITHUB_TOKEN: ${{ github.token }}
 
       - name: Run TFLint
         run: |
-          tflint --recursive --chdir=examples --config=$(pwd)/.terraform-governance/tflint.examples.hcl --format=compact
-          tflint --config=$(pwd)/.terraform-governance/tflint.hcl --format=compact
+          tflint --recursive --chdir=examples --config=$(pwd)/.terraform-governance/config/tflint.examples.hcl --format=compact
+          tflint --config=$(pwd)/.terraform-governance/config/tflint.hcl --format=compact
