Print warning if terraform-docs config file differs from expected (#91)
Signed-off-by: Roman Schwarz <rs@cloudeteer.de>

diff --git a/.github/workflows/module-ci-documentation.yaml b/.github/workflows/module-ci-documentation.yaml
--- a/.github/workflows/module-ci-documentation.yaml
+++ b/.github/workflows/module-ci-documentation.yaml
@@ -23,13 +23,15 @@ jobs:
       - name: Compare terraform-docs configuration files
         continue-on-error: true
         run: |
-          diff -u .terraform-governance/config/terraform-docs.yaml .terraform-docs.yaml
-          result=$?
-
-          if [ $result -eq 1 ]; then
+          if diff -u .terraform-governance/config/terraform-docs.yaml .terraform-docs.yaml > /dev/null; then
+            echo "No differences found in terraform-docs.yaml"
+          else
+            result=$?
+            if [ $result -eq 1 ]; then
             echo "::warning::Your local .terraform-docs.yaml file is different from the default one in the cloudeteer/terraform-governance repository. Please update your configuration file accordingly to make sure you have consistent documentation results."
-          elif [ $result -ge 1 ]; then
-            exit $result
+            elif [ $result -gt 1 ]; then
+              echo "::error::An error occurred while comparing .terraform-docs.yaml files."
+            fi
           fi
 
       - name: Check for diff in terraform-docs
